/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js type declarations and kept checked in for
// a predictable fresh clone experience.

